In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
train=pd.read_csv('train.csv')

In [3]:
test=pd.read_csv('test.csv')

In [4]:
macro=pd.read_excel('macro_economic.xlsx')

In [5]:
weath=pd.read_excel('weather1.xlsx')

In [6]:
print('Columns of train:',train.columns)
print('Columns of test:',test.columns)
print('Columns of macro:',macro.columns)
print('Columns of weather:',weath.columns)

Columns of train: Index(['Year', 'Month', 'ProductCategory', 'Sales(In ThousandDollars)'], dtype='object')
Columns of test: Index(['Year', 'Month', 'ProductCategory', 'Sales(In ThousandDollars)'], dtype='object')
Columns of macro: Index(['Year-Month', 'Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'PartyInPower',
       'unemployment rate', 'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'AdvertisingExpenses (in Thousand Dollars)',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports'],
      dtype='object')
Columns of weather: Index(['Year

In [7]:
macro['Year'] = macro['Year-Month'].str[:4].astype(int)
macro['Month'] = macro['Year-Month'].str[-3:].replace({'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,'Jul':7,'Aug':8,
                                'Sep':9,'Oct':10,'Nov':11,'Dec':12})

In [8]:
macro=macro.drop(['Year-Month','AdvertisingExpenses (in Thousand Dollars)','PartyInPower'],axis=1)

In [9]:
macro.isnull().sum()

Monthly Nominal GDP Index (inMillion$)                               0
Monthly Real GDP Index (inMillion$)                                  0
CPI                                                                  0
unemployment rate                                                    0
CommercialBankInterestRateonCreditCardPlans                          0
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    0
Earnings or wages  in dollars per hour                               0
Cotton Monthly Price - US cents per Pound(lbs)                       0
Change(in%)                                                          0
Average upland planted(million acres)                                0
Average upland harvested(million acres)                              0
yieldperharvested acre                                               0
Production (in  480-lb netweright in million bales)                  0
Mill use  (in  480-lb netweright in million bales)                   0
Export

In [10]:
weath.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2922 entries, 0 to 2921
Data columns (total 23 columns):
Year                           2922 non-null int64
Month                          2922 non-null object
Day                            2922 non-null int64
Temp high (°C)                 2922 non-null object
Temp avg (°C)                  2922 non-null object
Temp low (°C)                  2922 non-null object
Dew Point high (°C)            2922 non-null object
Dew Point avg (°C)             2922 non-null object
Dew Point low (°C)             2922 non-null object
Humidity (%) high              2922 non-null object
Humidity (%) avg               2922 non-null object
Humidity (%) low               2922 non-null object
Sea Level Press. (hPa) high    2922 non-null object
Sea Level Press. (hPa) avg     2922 non-null object
Sea Level Press. (hPa) low     2922 non-null object
Visibility (km) high           2922 non-null object
Visibility (km) avg            2922 non-null object
Visibility 

In [11]:
weath['Month'].value_counts()

Oct    248
May    248
Aug    248
Jul    248
Mar    248
Jan    248
Dec    248
Nov    240
Apr    240
Jun    240
Sep    240
Feb    226
Name: Month, dtype: int64

In [12]:
weath.isnull().sum()

Year                              0
Month                             0
Day                               0
Temp high (°C)                    0
Temp avg (°C)                     0
Temp low (°C)                     0
Dew Point high (°C)               0
Dew Point avg (°C)                0
Dew Point low (°C)                0
Humidity (%) high                 0
Humidity (%) avg                  0
Humidity (%) low                  0
Sea Level Press. (hPa) high       0
Sea Level Press. (hPa) avg        0
Sea Level Press. (hPa) low        0
Visibility (km) high              0
Visibility (km) avg               0
Visibility (km) low               0
Wind (km/h) low                   0
Wind (km/h) avg                   0
Wind (km/h) high                  0
Precip. (mm) sum                  0
WeatherEvent                   1908
dtype: int64

In [13]:
weath['WeatherEvent'].value_counts()

Rain                 685
Fog , Rain           156
Snow                  72
Fog , Snow            39
Rain , Snow           27
Fog , Rain , Snow     22
Fog                   12
Thunderstorm           1
Name: WeatherEvent, dtype: int64

In [14]:
weath['Precip.\xa0(mm) sum'].value_counts()

0         1754
T          205
0.25        86
0.51        57
0.76        45
          ... 
28.7         1
46.23        1
147.57       1
33.53        1
39.37        1
Name: Precip. (mm) sum, Length: 179, dtype: int64

In [15]:
for c in weath.columns:
    print( "---- %s ---" % c)
    print(weath[c].value_counts())

---- Year ---
2016    366
2012    366
2015    365
2013    365
2011    365
2009    365
2014    365
2010    365
Name: Year, dtype: int64
---- Month ---
Oct    248
May    248
Aug    248
Jul    248
Mar    248
Jan    248
Dec    248
Nov    240
Apr    240
Jun    240
Sep    240
Feb    226
Name: Month, dtype: int64
---- Day ---
1     96
28    96
4     96
6     96
8     96
10    96
12    96
14    96
16    96
18    96
20    96
22    96
24    96
26    96
2     96
3     96
5     96
7     96
9     96
11    96
13    96
15    96
17    96
19    96
21    96
23    96
25    96
27    96
29    90
30    88
31    56
Name: Day, dtype: int64
---- Temp high (°C) ---
28      140
27      124
29      114
22      112
18      110
26      109
23      104
21      100
12       98
31       97
14       96
8        92
17       90
19       89
7        88
24       87
4        86
16       86
13       84
32       83
11       80
6        73
3        70
9        66
2        59
30       54
10       53
1        52
15       50
33  

In [16]:
for i in weath.columns:
    weath[i]=weath[i].replace('-',np.nan)

In [17]:
print(weath.loc[weath['Wind\xa0(km/h) high'] == 'high'])

      Year Month  Day Temp high (°C) Temp avg (°C) Temp low (°C)  \
1826  2014   Jan    1           high           avg           low   

     Dew Point high (°C) Dew Point avg (°C) Dew Point low (°C)  \
1826                high                avg                low   

     Humidity (%) high  ... Sea Level Press. (hPa) avg  \
1826              high  ...                        avg   

     Sea Level Press. (hPa) low Visibility (km) high Visibility (km) avg  \
1826                        low                 high                 avg   

     Visibility (km) low Wind (km/h) low Wind (km/h) avg Wind (km/h) high  \
1826                 low             low             avg             high   

     Precip. (mm) sum WeatherEvent  
1826              sum          NaN  

[1 rows x 23 columns]


In [18]:
weath.drop(weath.index[1826],inplace=True)

In [19]:
print(weath.loc[weath['Wind\xa0(km/h) high'] == 'high'])

Empty DataFrame
Columns: [Year, Month, Day, Temp high (°C), Temp avg (°C), Temp low (°C), Dew Point high (°C), Dew Point avg (°C), Dew Point low (°C), Humidity (%) high, Humidity (%) avg, Humidity (%) low, Sea Level Press. (hPa) high, Sea Level Press. (hPa) avg, Sea Level Press. (hPa) low, Visibility (km) high, Visibility (km) avg, Visibility (km) low, Wind (km/h) low, Wind (km/h) avg, Wind (km/h) high, Precip. (mm) sum, WeatherEvent]
Index: []

[0 rows x 23 columns]


In [20]:
weath=weath.drop(['Precip.\xa0(mm) sum','WeatherEvent'],axis=1)

In [21]:
weath['Month']=weath['Month'].replace({'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,'Jul':7,'Aug':8,
                                'Sep':9,'Oct':10,'Nov':11,'Dec':12})

In [22]:
weath.dropna(inplace=True)

In [23]:
for i in weath.columns:
    weath[i]=weath[i].astype(float)

In [24]:
weath['Year']=weath['Year'].astype('int64')

In [25]:
weath['Month']=weath['Month'].astype('int64')

In [26]:
weath.dtypes

Year                             int64
Month                            int64
Day                            float64
Temp high (°C)                 float64
Temp avg (°C)                  float64
Temp low (°C)                  float64
Dew Point high (°C)            float64
Dew Point avg (°C)             float64
Dew Point low (°C)             float64
Humidity (%) high              float64
Humidity (%) avg               float64
Humidity (%) low               float64
Sea Level Press. (hPa) high    float64
Sea Level Press. (hPa) avg     float64
Sea Level Press. (hPa) low     float64
Visibility (km) high           float64
Visibility (km) avg            float64
Visibility (km) low            float64
Wind (km/h) low                float64
Wind (km/h) avg                float64
Wind (km/h) high               float64
dtype: object

In [27]:
macro.dtypes

Monthly Nominal GDP Index (inMillion$)                               float64
Monthly Real GDP Index (inMillion$)                                  float64
CPI                                                                  float64
unemployment rate                                                    float64
CommercialBankInterestRateonCreditCardPlans                          float64
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    float64
Earnings or wages  in dollars per hour                               float64
Cotton Monthly Price - US cents per Pound(lbs)                       float64
Change(in%)                                                          float64
Average upland planted(million acres)                                float64
Average upland harvested(million acres)                              float64
yieldperharvested acre                                                 int64
Production (in  480-lb netweright in million bales)                  float64

In [28]:
weath.head()

Year  Month  Day  Temp high (°C)  Temp avg (°C)  Temp low (°C)  \
0  2009      1  1.0            -3.0           -6.0           -9.0   
1  2009      1  2.0             1.0           -2.0           -5.0   
2  2009      1  3.0             3.0            1.0           -2.0   
3  2009      1  4.0             6.0            1.0           -4.0   
4  2009      1  5.0             6.0            5.0            3.0   

   Dew Point high (°C)  Dew Point avg (°C)  Dew Point low (°C)  \
0                -16.0               -17.0               -19.0   
1                 -3.0                -7.0               -17.0   
2                 -5.0                -9.0               -13.0   
3                -10.0               -12.0               -13.0   
4                 -1.0                -5.0               -16.0   

   Humidity (%) high  ...  Humidity (%) low  Sea Level Press. (hPa) high  \
0               54.0  ...              32.0                       1025.0   
1               78.0  ...              36.0                       1022.0   
2               72.0  ...              35.0                       1018.0   
3               55.0  ...              29.0                       1020.0   
4               62.0  ...              33.0                       1016.0   

   Sea Level Press. (hPa) avg  Sea Level Press. (hPa) low  \
0                      1023.0                      1015.0   
1                      1012.0                      1007.0   
2                      1015.0                      1008.0   
3                      1017.0                      1015.0   
4                      1014.0                      1013.0   

   Visibility (km) high  Visibility (km) avg  Visibility (km) low  \
0                  16.0                 16.0                 16.0   
1                  16.0                 13.0                  2.0   
2                  16.0                 16.0                 16.0   
3                  16.0                 16.0                 16.0   
4                  16.0                 16.0                 16.0   

   Wind (km/h) low  Wind (km/h) avg  Wind (km/h) high  
0             37.0             18.0              60.0  
1             27.0             10.0              48.0  
2             27.0             16.0              42.0  
3             32.0             12.0              40.0  
4             23.0             11.0              34.0  

[5 rows x 21 columns]

In [29]:
weath['Year'].value_counts()

2013    364
2009    361
2010    360
2012    357
2016    353
2015    352
2011    352
2014    350
Name: Year, dtype: int64

In [30]:
y1 = weath[weath["Year"]== 2009]
y1_V = y1.groupby("Month", as_index=False).agg("mean")
y2 = weath[weath["Year"]== 2010]
y2_V = y2.groupby("Month", as_index=False).agg("mean")
y3 = weath[weath["Year"]== 2011]
y3_V = y3.groupby("Month", as_index=False).agg("mean")
y4 = weath[weath["Year"]== 2012]
y4_V = y4.groupby("Month", as_index=False).agg("mean")
y5 = weath[weath["Year"]== 2013]
y5_V = y5.groupby("Month", as_index=False).agg("mean")
y6 = weath[weath["Year"]== 2014]
y6_V = y6.groupby("Month", as_index=False).agg("mean")
y7 = weath[weath["Year"]== 2015]
y7_V = y7.groupby("Month", as_index=False).agg("mean")
y8 = weath[weath["Year"]== 2016]
y8_V = y8.groupby("Month", as_index=False).agg("mean")

In [31]:
weath=pd.concat([y1_V,y2_V,y3_V,y4_V,y5_V,y6_V,y7_V,y8_V])

In [32]:
weath=weath.drop('Day',axis=1)

In [33]:
train['Datatype']='train'
test['Datatype']='test'

In [34]:
#test=test[train.columns]
d1=pd.concat([train,test],axis=0)

In [35]:
d1.head(2)

Year  Month ProductCategory  Sales(In ThousandDollars) Datatype
0  2009      1   WomenClothing                     1755.0    train
1  2009      1     MenClothing                      524.0    train

In [36]:
d1.shape

(252, 5)

In [37]:
d1['ProductCategory']=d1['ProductCategory'].replace(['MenClothing','WomenClothing','OtherClothing'],[1,2,3])

In [38]:
d2=pd.merge(d1,macro)

In [39]:
d2.head()

Year  Month  ProductCategory  Sales(In ThousandDollars) Datatype  \
0  2009      1                2                     1755.0    train   
1  2009      1                1                      524.0    train   
2  2009      1                3                      936.0    train   
3  2009      2                2                     1729.0    train   
4  2009      2                1                      496.0    train   

   Monthly Nominal GDP Index (inMillion$)  \
0                            14421.752895   
1                            14421.752895   
2                            14421.752895   
3                            14389.200466   
4                            14389.200466   

   Monthly Real GDP Index (inMillion$)      CPI  unemployment rate  \
0                         14407.053343  233.402                7.8   
1                         14407.053343  233.402                7.8   
2                         14407.053343  233.402                7.8   
3                         14366.176571  234.663                8.3   
4                         14366.176571  234.663                8.3   

   CommercialBankInterestRateonCreditCardPlans  \
0                                        12.03   
1                                        12.03   
2                                        12.03   
3                                        12.97   
4                                        12.97   

   Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan  \
0                                              11.44                   
1                                              11.44                   
2                                              11.44                   
3                                              11.05                   
4                                              11.05                   

   Earnings or wages  in dollars per hour  \
0                                   22.05   
1                                   22.05   
2                                   22.05   
3                                   22.22   
4                                   22.22   

   Cotton Monthly Price - US cents per Pound(lbs)  Change(in%)  \
0                                           57.70         4.02   
1                                           57.70         4.02   
2                                           57.70         4.02   
3                                           55.21        -4.32   
4                                           55.21        -4.32   

   Average upland planted(million acres)  \
0                                  9.296   
1                                  9.296   
2                                  9.296   
3                                  9.296   
4                                  9.296   

   Average upland harvested(million acres)  yieldperharvested acre  \
0                                    7.559                     799   
1                                    7.559                     799   
2                                    7.559                     799   
3                                    7.559                     799   
4                                    7.559                     799   

   Production (in  480-lb netweright in million bales)  \
0                                             12.589     
1                                             12.589     
2                                             12.589     
3                                             12.589     
4                                             12.589     

   Mill use  (in  480-lb netweright in million bales)  Exports  
0                                               4.17     11.55  
1                                               4.17     11.55  
2                                               4.17     11.55  
3                                               3.87     11.10  
4                                               3.87     11.10

In [40]:
df=pd.merge(d2,weath)

In [41]:
df.head()

Year  Month  ProductCategory  Sales(In ThousandDollars) Datatype  \
0  2009      1                2                     1755.0    train   
1  2009      1                1                      524.0    train   
2  2009      1                3                      936.0    train   
3  2009      2                2                     1729.0    train   
4  2009      2                1                      496.0    train   

   Monthly Nominal GDP Index (inMillion$)  \
0                            14421.752895   
1                            14421.752895   
2                            14421.752895   
3                            14389.200466   
4                            14389.200466   

   Monthly Real GDP Index (inMillion$)      CPI  unemployment rate  \
0                         14407.053343  233.402                7.8   
1                         14407.053343  233.402                7.8   
2                         14407.053343  233.402                7.8   
3                         14366.176571  234.663                8.3   
4                         14366.176571  234.663                8.3   

   CommercialBankInterestRateonCreditCardPlans  ...  Humidity (%) low  \
0                                        12.03  ...         42.322581   
1                                        12.03  ...         42.322581   
2                                        12.03  ...         42.322581   
3                                        12.97  ...         38.107143   
4                                        12.97  ...         38.107143   

   Sea Level Press. (hPa) high  Sea Level Press. (hPa) avg  \
0                  1021.290323                 1015.967742   
1                  1021.290323                 1015.967742   
2                  1021.290323                 1015.967742   
3                  1021.714286                 1017.071429   
4                  1021.714286                 1017.071429   

   Sea Level Press. (hPa) low  Visibility (km) high  Visibility (km) avg  \
0                 1010.516129                  16.0            14.000000   
1                 1010.516129                  16.0            14.000000   
2                 1010.516129                  16.0            14.000000   
3                 1012.464286                  16.0            15.178571   
4                 1012.464286                  16.0            15.178571   

   Visibility (km) low  Wind (km/h) low  Wind (km/h) avg  Wind (km/h) high  
0            11.451613        27.000000        12.000000         39.322581  
1            11.451613        27.000000        12.000000         39.322581  
2            11.451613        27.000000        12.000000         39.322581  
3            13.285714        27.928571        12.214286         41.642857  
4            13.285714        27.928571        12.214286         41.642857  

[5 rows x 38 columns]

In [42]:
df.shape

(252, 38)

In [43]:
df=pd.get_dummies(data=df, columns=['Month', 'ProductCategory'])

In [44]:
df.columns

Index(['Year', 'Sales(In ThousandDollars)', 'Datatype',
       'Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'unemployment rate',
       'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'Temp high (°C)', 'Temp avg (°C)', 'Temp low (°C)',
       'Dew Point high (°C)', 'Dew Point avg (°C)', 'Dew Point low (°C)',
       'Humidity (%) high', 'Humidity (%) avg', 'Humidity (%) low',
       'Sea Level Press. (hPa) high', 'Sea Level Press. (hPa) avg',
       'Sea Level Press. (hPa) low', 'Visib

In [ ]:
d = d.drop(['Temp high (°C)'],axis=1)
d = d.drop(['Temp low (°C)'],axis=1)
d = d.drop(['Dew Point high (°C)'],axis=1)
d = d.drop(['Dew Point low (°C)'],axis=1)
d = d.drop(['Humidity (%) high'],axis=1)
d = d.drop(['Humidity (%) low'],axis=1)
d = d.drop(['Visibility (km) high'],axis=1)
d = d.drop(['Visibility (km) low'],axis=1)
d = d.drop(['Wind (km/h) high'],axis=1)
d = d.drop(['Wind (km/h) low'],axis=1)
d = d.drop(['Sea Level Press. (hPa) high'],axis=1)
d = d.drop(['Sea Level Press. (hPa) low'],axis=1)

In [45]:
df_train=df[df['Datatype']=='train']
del df_train['Datatype']
df_test=df[df['Datatype']=='test']
df_test.drop(['Datatype'],axis=1,inplace=True)

In [46]:
del df

In [47]:
df_train['Sales(In ThousandDollars)']=df_train['Sales(In ThousandDollars)'].fillna(method='ffill')

In [48]:
df_test=df_test.drop('Sales(In ThousandDollars)',axis=1)

In [49]:
X=df_train.drop('Sales(In ThousandDollars)',axis=1)
y=df_train['Sales(In ThousandDollars)']

In [76]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, fbeta_score, accuracy_score

In [72]:
clf = DecisionTreeRegressor()

parameters = {'max_depth':(1,2,3,4,5,6,7,8,9,10)},{'min_samples_split': (0.1,0.2,0.3,0.4,0.5)},
{'min_samples_leaf': (1,2,3,4,5,6,7)},{'min_weight_fraction_leaf': (0.0,0.1,0.2)}

#scorer = make_scorer(fbeta_score,beta=0.5)

grid_obj = GridSearchCV(clf, param_grid = parameters)
grid_fit = grid_obj.fit(X,y)

best_clf = grid_fit.best_estimator_
predictions = (clf.fit(X, y)).predict(df_test)
best_predictions = best_clf.predict(df_test)

In [73]:
best_clf

DecisionTreeRegressor(criterion='mse', max_depth=1, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [74]:
from sklearn.ensemble import AdaBoostRegressor


regr2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=1,criterion='mse',min_samples_leaf=1,
                      min_samples_split=2),n_estimators=100, random_state=None)

regr2.fit(X,y)

pred_new =(regr2.predict(df_test))

In [75]:
pred_new

array([3352.54945055, 1723.48648649, 1723.48648649, 3100.65384615,
       1723.48648649, 1723.48648649, 3100.65384615, 1723.48648649,
       1723.48648649, 3100.65384615, 1723.48648649, 1723.48648649,
       3352.54945055, 1723.48648649, 1723.48648649, 3100.65384615,
       1723.48648649, 1723.48648649, 3100.65384615, 1723.48648649,
       1723.48648649, 3180.45783133, 1723.48648649, 1723.48648649,
       3180.45783133, 1723.48648649, 1723.48648649, 3180.45783133,
       1723.48648649, 1723.48648649, 3352.54945055, 1723.48648649,
       1723.48648649, 3414.33333333, 1723.48648649, 1723.48648649])

In [71]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':pred_new})
submitdf.to_csv('new.csv',index=False)

In [77]:
from sklearn.ensemble import RandomForestRegressor
rfg=RandomForestRegressor(random_state=1)
param_dist = {'n_estimators': (1,3,5,14,10,20,50),'max_depth': [2, 3, 4,10],'bootstrap': [True, False],
              'max_features': ['auto', 'sqrt', 'log2', None],
              'criterion': ['mse', 'mae']}

cv_rf = GridSearchCV(rfg, cv = 5 ,param_grid=param_dist, n_jobs = 3)
cv_rf.fit(X,y)
rfpred=cv_rf.predict(df_test)

C:\Users\RADHAKRISHNA\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [79]:
rfpred

array([3528.5,  669. , 1049. , 3528.5,  669. , 1049. , 3528.5,  669. ,
       1049. , 3528.5,  669. , 1049. , 3528.5,  669. , 1049. , 3528.5,
        669. , 1049. , 3528.5,  669. , 1049. , 3528.5,  669. , 1049. ,
       3528.5,  669. , 1049. , 3528.5,  669. , 1049. , 3528.5,  669. ,
       1049. , 3528.5,  669. , 1049. ])

In [81]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':rfpred})
submitdf.to_csv('new.csv',index=False)

In [88]:
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV,ShuffleSplit

In [105]:
ada_classifier = AdaBoostRegressor(random_state=42)
#cv_sets = ShuffleSplit(random_state = 4) # shuffling our data for cross-validation
parameters = {'n_estimators':(1,200,2), 
              'learning_rate':[0.05, 0.1, 0.15, 0.2]}
#scorer = make_scorer(f1_score)
ada_obj = RandomizedSearchCV(ada_classifier, 
                              parameters, 
      #                        scoring = scorer, 
    #                          cv = cv_sets,
                              random_state= 99)
ada_fit = ada_obj.fit(X, y)
ada_opt = ada_fit.best_estimator_

In [106]:
ada_fit.best_params_

{'n_estimators': 200, 'learning_rate': 0.1}

In [107]:
ada_opt

AdaBoostRegressor(base_estimator=None, learning_rate=0.1, loss='linear',
                  n_estimators=200, random_state=42)

In [108]:
ada_obj = AdaBoostRegressor(learning_rate = 0.1,
                             n_estimators = 200,
                            loss='linear',
                             random_state=1)
ada_opt = ada_obj.fit(X, y)

In [109]:
y_pred_ada = ada_opt.predict(df_test)
y_pred_ada

array([3918.57692308,  937.        , 1069.        , 3793.18518519,
        902.72093023, 1056.        , 3816.125     ,  904.86440678,
       1056.        , 3793.67857143,  913.81081081, 1056.        ,
       3883.13636364, 1193.16666667, 1056.        , 3711.44444444,
        959.26315789, 1056.        , 3711.44444444, 1453.02564103,
       1124.        , 3762.31578947, 1812.03448276, 1124.76923077,
       3843.28      , 1320.30769231, 1056.        , 3843.28      ,
        940.73381295, 1056.        , 3894.03030303, 1388.41666667,
       1078.18181818, 4632.55172414,  974.42622951, 1140.03389831])

In [110]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':y_pred_ada})
submitdf.to_csv('new.csv',index=False)

In [114]:
from sklearn.ensemble import GradientBoostingRegressor
GBC_regressor = GradientBoostingRegressor(random_state=42)
#cv_sets = ShuffleSplit(random_state = 4) # shuffling our data for cross-validation
parameters = {'n_estimators':(1,500,2), 
              'learning_rate':[0.01, 0.03, 0.05],
              'min_samples_split':[2,4,6],
              'min_samples_leaf':[3,5,7]}
#scorer = make_scorer(f1_score)
GBC_obj = RandomizedSearchCV(GBC_regressor, 
                             parameters, 
    #                         scoring = scorer, 
 #                            cv = cv_sets,
                             random_state= 99)
GBC_fit = GBC_obj.fit(X, y)
GBC_opt = GBC_fit.best_estimator_

In [115]:
GBC_opt

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.03, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=5, min_samples_split=6,
                          min_weight_fraction_leaf=0.0, n_estimators=500,
                          n_iter_no_change=None, presort='auto',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [116]:
GBC_fit.best_params_

{'n_estimators': 500,
 'min_samples_split': 6,
 'min_samples_leaf': 5,
 'learning_rate': 0.03}

In [117]:
GBC_obj = GradientBoostingRegressor(learning_rate = 0.03,
                                    criterion='friedman_mse',
                                     max_depth = 3,
                                     min_samples_leaf = 5,
                                     min_samples_split = 6,
                                     n_estimators = 500,
                                     random_state=42)
GBC_opt = GBC_obj.fit(X, y)

In [118]:
y_pred_gbc = GBC_opt.predict(df_test)
y_pred_gbc

array([4057.97868447, 1030.18228388, 1607.49840034, 4216.98173401,
        954.0453447 , 1511.52392047, 4282.96482136,  907.67855593,
       1504.46900759, 4490.88055676, 1287.43065083, 1441.72042185,
       4495.72451679, 1438.05114349, 1618.85495955, 4106.0749495 ,
       1023.28630741, 1442.03017152, 3898.46141003,  974.9849434 ,
       1095.33190174, 4039.45282128, 1270.78063717,  871.76152628,
       4591.84946866, 1452.91896051, 1354.8825118 , 4464.1112561 ,
       1332.79012109, 1493.15987638, 4578.12771758, 1790.00711175,
       1556.42173109, 5186.10085527, 1072.7964797 , 1702.09820865])

In [119]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':y_pred_ada})
submitdf.to_csv('new.csv',index=False)

In [121]:
!pip install xgboost

In [122]:
from xgboost import XGBRegressor

In [124]:
xb=XGBRegressor()
xb.fit(X,y)
xpred=xb.predict(df_test)

[16:14:23] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [126]:
xpred

array([3691.5603, 1179.948 , 1455.5898, 4015.7937, 1136.9655, 1422.8804,
       4205.017 , 1203.9268, 1428.5912, 4393.0034, 1217.4998, 1499.6853,
       4485.1436, 1364.7817, 1462.957 , 3950.719 , 1253.0756, 1353.5796,
       4147.7427, 1289.4866, 1257.4517, 4015.34  , 1328.894 , 1154.372 ,
       4152.864 , 1369.5875, 1039.4946, 4006.4766, 1262.0994, 1307.1486,
       4428.9014, 1422.5687, 1487.6763, 4935.8057, 1067.6829, 1644.3497],
      dtype=float32)

In [127]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':xpred})
submitdf.to_csv('new.csv',index=False)

In [136]:
model=DecisionTreeRegressor()
ada_obj = AdaBoostRegressor(base_estimator=model,
    learning_rate = 0.01,
                             n_estimators = 100,
                        
                             random_state=100)
ada_opt = ada_obj.fit(X, y)

In [137]:
pred=ada_opt.predict(df_test)

In [138]:
pred

array([4421.,  757., 1468., 4268.,  636., 1337., 4421.,  757., 1337.,
       4268.,  731., 1293., 4434.,  749., 1229., 4421.,  702., 1257.,
       4067.,  692., 1293., 4067.,  702., 1153., 4067.,  731., 1155.,
       4434.,  785., 1209., 4434.,  785., 1252., 4865., 1070., 1566.])

In [139]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':xpred})
submitdf.to_csv('new.csv',index=False)

In [142]:
from sklearn.tree import DecisionTreeRegressor
giniDecisionTree = DecisionTreeRegressor(random_state = 100,max_depth=3, min_samples_leaf=5)

giniDecisionTree.fit(X,y)

giniPred = giniDecisionTree.predict(df_test)
giniPred

array([4416.90909091,  677.66101695, 1095.69491525, 4416.90909091,
        677.66101695, 1095.69491525, 4416.90909091,  677.66101695,
       1095.69491525, 4416.90909091,  677.66101695, 1095.69491525,
       4416.90909091,  677.66101695, 1095.69491525, 4416.90909091,
        677.66101695, 1095.69491525, 4416.90909091,  801.85714286,
        801.85714286, 4416.90909091,  801.85714286,  801.85714286,
       4416.90909091,  801.85714286,  801.85714286, 4416.90909091,
        677.66101695, 1095.69491525, 4416.90909091,  677.66101695,
       1095.69491525, 4416.90909091,  677.66101695, 1095.69491525])

In [143]:
submitdf = pd.DataFrame({'S.No.':np.arange(1,37), 'Sales':giniPred})
submitdf.to_csv('new.csv',index=False)